### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by finnie2006** [HM4Development/mcpaste-addon#1]
1: it works really great
but do i need to install it again after a update if thats yes maybe its nice to make a install script command then

**Comment by Hitman4123** [comment]
Yes, You do have to reinstall the addon after you update the pterodactyl panel. I will look into making an install script.

**Comment by finnie2006** [comment]
@Hitman4123 I maded a install script tested works 100%

https://github.com/finnie2006/MCpastepteroinstaller
