### ISSUE TITLE
Display more information about server

### ISSUE THREAD

**Issue by ririko5834** [HM4Development/mcpaste-addon#2]
Hi, I think that the log that is uploaded to mcpaste should include more information, make some head where will be for example:
```
Logs from pterodactyl server
Uploaded using MCPaste pterodactyl add-on (github.com/HM4Development/mcpaste-addon)
--------------------------------------------------------------------
Uploaded on: date when logs were uploaded to haste
Server name: server name
Server ID: server id
Server node: server node
Server state: running/starting/offline
Server CPU: used/available
Server RAM: used/available
Server Disk: used/available
Server docker image: docker image link
Server egg: server egg name
Server owner: first and last name of owner + email
--------------------------------------------------------------------
here will be the logs

```

It will be helpful to investigate the issue  better and faster

**Comment by Hitman4123** [comment]
A big update is coming to the mcpaste addon very soon! We will be adding that feature.

**Comment by ririko5834** [comment]
Great, I can't wait until it will be added. And this will be good when the user sends the logs to support so they can investgate the issue better, and maybe display there also server link
