### ISSUE TITLE
Issue with 2.0

### ISSUE THREAD

**Issue by JohnB17** [HM4Development/mcpaste-addon#4]
I'm having an issue, my panel and node are private (Only accessible within this building) and whenever I try to send a log I get:
```Couldn't share log. Error: Unauthorized domain!```

**Comment by Antony1060** [comment]
Are you sure that the domain you authorized with your token matches your panels domain, this doesn't matter if the panel itself is private or not.

**Comment by JohnB17** [comment]
The domain was "panel.example.com" (internally) and in the api settings I set it to "panel.example.com" and updated the key.

**Comment by Antony1060** [comment]
Our records don't show any token registered with `panel.example.com`. You must match the domain that you access your panel from with the domain registered with the token.. For quicker support, please contact us on our discord server: https://discord.gg/rN3qaSVPyb
