### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by Waffleuncle** [HM4Development/mcpaste-addon#6]
![image](https://user-images.githubusercontent.com/76669896/128407948-14dd85f4-7892-4680-bfec-9bb72c8ad5cc.png)

**Comment by Antony1060** [comment]
Your node modules didn't seem to resolve correctly. Make sure you're using the latest version of node.js. Also, when making issues, it is nice to provide a bit more information like the panel version you're using.

**Comment by Waffleuncle** [comment]
I got this logs , 
And now after installing your addons broke hole panel 
https://i.imgur.com/s3D4E3I.png

**Comment by stijnb1234** [comment]
It's the best to use the package.json / yarn.lock provided by Pterodactyl, and run `yarn add strip-ansi` yourself, before building the panel.

**Comment by Antony1060** [comment]
> It's the best to use the package.json / yarn.lock provided by Pterodactyl, and run `yarn add strip-ansi` yourself, before building the panel.

True, will implement this in the next update.
