### ISSUE TITLE
Add hastebin option

### ISSUE THREAD

**Issue by ririko5834** [HM4Development/mcpaste-addon#8]
Add option that you can set custom hastebin URL in settings where it will be uploaded.

**Comment by Hitman4123** [comment]
Custom Hastebin servers will not be supported.

**Comment by ririko5834** [comment]
Um and why?

**Comment by Hitman4123** [comment]
Because you will soon be able to fully customized and rename mcpaste.com 

Like (myhosting.mcpaste.com) or (serverlogs.myhosting.com)

**Comment by Antony1060** [comment]
Also, there is no intention currently to support custom hastebin servers. Our addon intended as a compatibility layer for _our_ service.
